#   -*- mode: org; fill-column: 60 -*-
#+TITLE: How We Work
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/docs/hb-how-we-work.org
  :Created:   2017-05-20T14:41@Prek Leap (11.642600N-104.919210W)
  :ID:        67f807cf-a4dd-4f09-b7e7-ef40fd00f647
  :VER:       548538140.395599462
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:DNH8-5187
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

#+begin_comment
I just want to go to sleep, but have to wait for SINet to call back
about the campus internet connection...

So what will this page be for?

I think this will be the generalized chenla-specific version of /how
we work/.  The other files, workflow, methodologies, communication etc
are more background and why we work the way we do.  After all, we are
as much an academic group as much as developers, engineers and
scientists.  This is needed because many of the things we will do here
will be applicable to human and machine distributed systems we are
developing.

So in a sense this will be the team handbook....

And yes I am extremely aware that I am writing a handbook for a team
of one person at the moment -- build it and they will come, I
suppose....

#+end_comment
