#   -*- mode: org; fill-column: 60 -*-

#+TITLE: How We Work
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/docs/hb-how-we-work.org
:Created:   2017-05-20T14:41@Prek Leap (11.642600N-104.919210W)
:ID:        67f807cf-a4dd-4f09-b7e7-ef40fd00f647
:VER:       551835706.986341363
:GEO:       48P-491193-1287029-15
:BXID:      chenla:HJQ1-1487
:Class:     deploy
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

#+begin_quote
[in the waiting room of the afterlife]

*Barbara:* Adam, is this what happens when you die?

*Receptionist:* This is what happens when /you/ die.

[points at a gaunt man smoking]

*Receptionist:* That is what happens when /he/ dies.

[points at a woman cut in half on the sofa reading]

*Receptionist:* And that is what happens when /they/ die. It's all
very personal. 

-- Bettlejuice (1988)
#+end_quote


It's a bit of a misnomer to state /How We Work/, because, like the
receptionist in the afterlife in Bettlejuice said, /it's all very
personal/.  We all work in different ways, there is no one size fits
all.  We work differently at an organizational level than at the
project level and team level work is different from how we work as
individuals.  And no two projects, teams or individuals work quite the
same.  That said, there are patterns to the way we work, and work
together.

And there are tools, proceedures, processes and structure that runs
through our work like a theme in bebop, a structure that you can
modulate, and improvise so that no matter how far afield you go, you
can still hear it, winding through the complex sequence of altered
chords that give us freedom and strength through discipline and
structure so the work can always move forward as one.

There /are/ ways that we don't work and manage.  We abhore dogmatic
truth and ideologies of all stripes in all their many guises.  We are
not snowflakes.  If anything makes us special it is achieved through
humility and dogged perseverance.  We don't do command structures or
waterfalls, trends, and memes.  We are neither flat nor a tree, neither
linear nor rhizomatic.  We embrace duality, complexity, and paradoxes
and revel in their beauty and accept the limits of what we can know,
all the while pushing the boundries and expanding what is known.

