#   -*- mode: org; fill-column: 60 -*-
#+TITLE: How We Work
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/docs/hb-how-we-work.org
  :Created:   2017-05-20T14:41@Prek Leap (11.642600N-104.919210W)
  :ID:        67f807cf-a4dd-4f09-b7e7-ef40fd00f647
  :VER:       548538140.395599462
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:DNH8-5187
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

#+begin_comment
I just want to go to sleep, but have to wait for SINet to call back
about the campus internet connection...

So what will this page be for?

I think this will be the generalized chenla-specific version of /how
we work/.  The other files, workflow, methodologies, communication etc
are more background and why we work the way we do.  After all, we are
as much an academic group as much as developers, engineers and
scientists.  This is needed because many of the things we will do here
will be applicable to human and machine distributed systems we are
developing.

So in a sense this will be the team handbook....

And yes I am extremely aware that I am writing a handbook for a team
of one person at the moment -- build it and they will come, I
suppose....

Hah! just checked and comment blocks AREN'T rendered by Github, so if
you're reading this, or any other of my snarky asides, you're reading
the source!
#+end_comment


#+begin_quote
[in the waiting room of the afterlife]

*Barbara:* Adam, is this what happens when you die?

*Receptionist:* This is what happens when *you* die.

[points at a gaunt man smoking]

*Receptionist:* That is what happens when *he* dies.

[points at a woman cut in half on the sofa reading]

*Receptionist:* And that is what happens when *they* die. It's all
very personal. 

-- Bettlejuice (1988)
#+end_quote


It's a bit of a misnomer to state /How We Work/, because, like the
receptionist in the afterlife in Bettlejuice said, /it's all very
personal/.  We all work in different ways, there is no one size fits
all.  We work differently at an organizational level, than at the
project level and team level work is different from how we work as
individuals.  And no two projects, teams or individuals work quite the
same.  That said, there are patterns to the way we work, and work
together.

And there are tools, proceedures, processes and structure that runs
through our work like a theme in bebop, a structure that you can
modulate, and improvise so that no matter how far afield you go, you
can still hear it, winding through the complex sequence of altered
chords that give us freedom and strength through discipline and
structure so the work can always move forward as one.

There /are/ ways that we don't work and manage.  We abhore dogmatic
truth and ideologies of all stripes in all their many guises.  We are
not snowflakes.  If anything makes us special it is achieved through
humility and dogged perseverance.  We don't do command structures or
waterfalls, trends, and memes.  We are neither flat nor a tree, neither
linear nor rhizomatic.  We embrace duality, complexity, and paradoxes
and revel in their beauty and accept the limits of what we can know,
all the while pushing the boundries and expanding what is known.

