#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Meetings Handbook
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/docs/hb-meetings.org
  :Created: 2017-01-31T17:00@Prek Leap (11.642600N-104.919210W)
  :ID: b3523298-7c79-4dc9-a1ac-b064e82d5ed3
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Introduction

Move material from hb-methodologies to here.....\

** Firefox IRC Standup Workflow

- [[https://wiki.mozilla.org/Standup][Standup]] | MozillaWiki
- [[https://github.com/mozilla/standup][mozilla/standup]] | Github
- [[https://github.com/mozilla/standup-irc][mozilla/standup-irc: Daily status IRC bot]] | Github
- [[https://wiki.mozilla.org/IRC][IRC]] | MozillaWiki]

How does this compare with Meetbot?

* Notes 

  - [[./hb-meetings.org]]
    - create a meeting
    - how to chair a meeting
    - meetbot docs
    
Can this bot work in #Slack?

----

meetings are scheduled -- there should be a page for the
schedule simular to the  [[http://eavesdrop.openstack.org/][OpenStack IRC meetings]] we should be
able to do this by email....

  - everything is logged and made logs linked to afterwards
  - install meetbot! and use for all meetings including
    standups, in person meetings, and video-conference
    code-reviews.

** Standup Meetings for Distributed Teams

When possible, do daily standups remotely, and Sprint
Reviews in person or video video.

#+begin_quote
The only time I’ve seen a standup work successfully is when
it wasn’t a standup at all but a status update posted via
Slack. Now, there’s the same format and the same time
constraint. You tell the team “at 9:45am (or whenever) you
need to post your status update”. But it gives them
flexibility. If they do some kind of personal productivity
mechanism like GTD or Pomodoro, they can copy in notes from
that system into the standup comment. They can keep notes
from the previous day. Being at their computer means they
can actually look at what is in front of them (Git commits,
issue tracker updates etc.) to determine what they are
working on, and they can link to those if they feel like it.

It gives more flexibility for remote workers or even just
people running a few minutes late for the office. Bus got
stuck in traffic? You can still post your update on Slack.

It gives more permanence. You can see what you posted
yesterday and see whether the things you said you’d do
yesterday were the things you actually did. This gives you
more accountability. Also, having a clear log of what you
did every day you worked helps when compiling timesheets, or
invoices if you are a contractor.

It prevents people from going off on pointless discussions
about stuff that is of no relevance to the rest of the
team. They can still discuss it, just not in the standup
channel.

-- [[https://tommorris.org/posts/9427][Standups: just use text (and maybe Slack)]]
#+end_quote


  - Everyone announce they are online
  - if you have a question, type ? 

Agendas have to be more formal than face-to-face meetings

First decide what technologies to use -- don't use video
conferencing unless it is rock solid for everyone in the
meeting -- in our experience, most video conferencing
meetings is spent in dealing with dropped connections,
mis-configured software, low-bandwidth, crappy microphones
and cameras etc, than is spent in the meeting itself.  Even
plain old telephone calls often suffer from not being able
to hear people.

If and when you do use video, make sure everyone has a
/good/ camera and headset.  There should be a
[[./howto--video-conference.org]] Video Conference HOWTO
for lighting, and test connections, lighting etc the day
before the meeting.

Standups work very well using IRC/Slack style chat.


* Example Meetbot IRC meeting

Here is a randomly chosen example of Meetbot's output and
a log of a meeting from the Debian project.

  - [[http://meetbot.debian.net/debian-edu/2010/debian-edu.2010-01-11-19.01.html][#debian-edu Meeting]]
  - [[http://meetbot.debian.net/debian-edu/2010/debian-edu.2010-01-11-19.01.log.html][#debian-edu log]]

#+begin_quote
A free and open source software project will have a
dedicated IRC channel where the project members will meet to
have discussions. Meetings can be scheduled, and can happen
in different time zones depending on where the users are
located. There is a protocol and etiquette to be followed
during such meetings. The speaker or moderator should not be
interrupted during the session.

If you wish to ask a question, type ’?’ and wait. When the
speaker has finished and feels that you can type in your
text, you will be asked to do so. After you have finished
typing your content, end with ‘EOF’. Similarly, if you need
to speak during the session, type ’!’, and wait. You can
give your consent or dissent to statements made in the
channel using +1 or -1, respectively.

-- [[http://www.shakthimaan.com/posts/2016/06/23/rcirc/news.html][Shakthimaan's Blog | GNU Emacs - rcirc IRC client]]
#+end_quote



* Further Reading

** Standup Meetings
 - [[http://www.teamreporterapp.com/virtual-stand-up-meetings-with-best-practices-and-alternatives/][Virtual Stand-up Meetings for Distributed Teams]] | Teamreporter
 - [[http://eavesdrop.openstack.org/][OpenStack IRC meetings]] 
 - [[https://wiki.openstack.org/wiki/Meetings/ChairaMeeting][Meetings/ChairaMeeting]] | OpenStack
 - [[https://wiki.openstack.org/wiki/Meetings/CreateaMeeting][Meetings/CreateaMeeting]] | OpenStack
 - [[https://wiki.openoffice.org/wiki/Community_Council/Meeting_Guidelines/Meeting_Guidelines_Development][Meeting Guidelines Development]] | Apache OpenOffice Wiki
 - [[https://wiki.openoffice.org/wiki/Community_Council/Meeting_Guidelines][Meeting Guidelines]] | Apache OpenOffice Wiki 
 - [[https://meta.wikimedia.org/wiki/IRC_office_hours/Guidelines][IRC office hours/Guidelines]] | Wikipedia Meta
 - [[https://meta.wikimedia.org/wiki/IRC/Instructions][IRC/Instructions]] | Wikipedia Meta

** IRC Meeting Bots
 - [[https://wiki.debian.org/MeetBot][MeetBot]] | Debian Wiki
 - [[https://github.com/openstack-infra/meetbot][openstack-infra/meetbot]] | Github
 - [[https://github.com/Supybot/Supybot][Supybot/Supybot]] | Github
