#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Master Plan
#+STARTUP: showall
#+PROPERTY: filename
:PROPERTIES:
:Name: /home/deerpig/proj/chenla/core-docs/master-plan.org
:Created: 2016-09-17T15:34@Prek Leap (11.642600N-104.919210W)
:ID: fa188367-d380-493a-b8d2-d70c12982248
:URL:
:END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Changes since version: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.01"
RES=`git log $TAG...HEAD --pretty="<li>%s</li>\n" -- master-plan.org`
if [ -z $RES ]; then
RES="<li>no changes</li>"
fi
echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction
* First Principles

It From Bit

  - information
  - energy
  - entropy

  - time is (+ entropy (or energy energy))
  - entropy and time are not reversible
  - life is a self organizing information machine -- goes against entropy

If it requires energy it is finite.

  - computation is finite
  - physical things are finite
  - computation is work
  - work expends energy
  
** Finite and Infinite Resources

  If I can take something, and it deprives someone of that thing, it
  is a finite resource.

  If I can make a copy of something and it doesn't deprive others of
  that thing than it is an infinite resource

* Encoding & Structure

 - primitives :: symbols, numbers, strings, lists
 - triples :: subject, predicate, object
 - directed property graphs :: edges and vertices where everything is
      a relationship.

* Context & Scale

 - LOD
 - POV
 - ROC

* Holons

No man is an island, he is a holon

It's holons, all the way down....

 - everything has a dual whole/part nature depending on POV and LOD
 - Everything can be viewed as an atom or a holon
 - atoms are mutually exclusive
 - holons are both:
    - self contained semi-autonmous wholes
    - parts of a larger structure

* Mind and Body

The mammal neocortex is a self-programing general purpose
computational engine.

- hierachical AND linear

** Extension of Cognition and Memory

- Life -> neocortex
- neocortex -> speech
- speech -> writing

- cognitive machines (computers)

** Extension of Muscle and the Senses

- dogs extended our smell and hearing
- tools extended out hands
- cows and horses extended our muscles

** Machines

- machines combine tools and external energy

** Robots

- robots are machines controlled by compters

* Mankind

 Mankind is more than the hominid homo sapien, 

 - we are a transactive species
 - we spread the load of cognition, memory and muscles between each
   other and other members of mankind, including dogs, and now
   computers and robots

* Homoiconographic

Equivalence of code and data

We need self-processing graphs -- processes -> the whole
graph is both code & data -- that runs everytime that the
graph changes -- change one thing and the change propagates
out through the whole graph and all other graphs connected
to it -- so yes, concurrency, going forward will be a big
thing.

* Building Blocks

We can build anything using four fundemental building blocks:

  - Process :: steps and rules
  - Message :: docs, messages, storage, blobs are are all messages --
       that are nodes in graphs that model a holon.  Messages have are
       anything that change state from one location, time, etc to another.
       storage is sending a message with a delay between sending and
       recieving.
   - State :: 
   - Relationship :: 

*** Work as a foundation for transactions

  - Providing energy & performing work generates tokens
  - Using energy destroys tokens
  - Using energy or work done by someone else transfers tokens from
    you to them. 
* Maps

Holons are extended and interact with each other through cognitive
maps which can be modeled as directed property graphs.

** Cognitive

A person is a holon that has a conception of self -- which is similar
too but not the same as self-awareness -- a term that carries a lot of
baggage.

Persons are a conceptual holon, they don't exists except as an
abstract self-consciousness;

Persons are a collection personas -- aspects of the self
that is used internally and or presented to the world as a
self-contained entity.

Personas are made up of roles -- roles are overlapping.

Persons Holons are modeled both in the brain and externally as a group
of overlapping, intersecting directed property graphs.  Each of these
graphs is a shard of a person, persona or role which we call a 
=horcrux=.

** Collective

*** Human thresholds -- memory, group size
*** levels of separation



** Inanimate
